name: ChunkCollector
version: '1.0'
main: bgprotobg.net.chunkcollector.ChunkCollector
api-version: '1.20'
softdepend:
  - AxBoosters
commands:
  chunkcollector:
    description: Gives a chunk collector to a player.
  sellwand:
    description: Command to give a SellWand to a player.
permissions:
  chunkcollector.give:
    description: Allows the player to give chunk collectors
    default: op